//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalOnlineSystemGroup12
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestsTable
    {
        public int TestID { get; set; }
        public int PatientID { get; set; }
        public string TestResults { get; set; }
        public System.DateTime TestDate { get; set; }
        public int DoctorID { get; set; }
    }
}
