//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalOnlineSystemGroup12
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTable
    {
        public string UserLoginName { get; set; }
        public string UserLoginPass { get; set; }
        public int UserIsDoctor { get; set; }
    }
}
